# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeconsole < Formula
  desc "Utility to create temporary REPL pods from deployments"
  homepage "https://github.com/micke/kubeconsole"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/micke/kubeconsole/releases/download/v1.1.1/kubeconsole_1.1.1_darwin_amd64.tar.gz"
      sha256 "218dc287d88e0a5efe7830ba2821f0cfa8e61a38782f1181c900c187575a12ab"
    end
    if Hardware::CPU.arm?
      url "https://github.com/micke/kubeconsole/releases/download/v1.1.1/kubeconsole_1.1.1_darwin_arm64.tar.gz"
      sha256 "ac64bbed3645807c5461a97da4184d7c0a1ad0ad2a9e4f227d7f9fcae2d26a7c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/micke/kubeconsole/releases/download/v1.1.1/kubeconsole_1.1.1_linux_amd64.tar.gz"
      sha256 "3c994e48d94bdabf945c3b9cb32503682cfc56965419a3815636c739dce4c45a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/micke/kubeconsole/releases/download/v1.1.1/kubeconsole_1.1.1_linux_arm64.tar.gz"
      sha256 "f0e5dfde3ad253660fea1495287a1b27c1a9b342347e604fc1228b5c6ef2ff6f"
    end
  end

  def install
    bin.install "kubeconsole"

    bash_completion.install "completions/kubeconsole.bash" => "kubeconsole"
    zsh_completion.install "completions/kubeconsole.zsh" => "_kubeconsole"
    fish_completion.install "completions/kubeconsole.fish" => "_kubeconsole"
  end

  test do
    system "#{bin}/kubeconsole", "--help"
  end
end
